### ISSUE TITLE
Docker doesn't appear to be running on the created agents

### ISSUE THREAD

**Issue by josh-stableprice** [gocd/docker-gocd-agent-dind#10]
I'm running a test task at the moment while I get things set up on kubernetes, however it's reporting that docker isn't running.

```
[go] Task: docker build --no-cache --tag imagename:latest --tag imagename:commit --label "org.label-schema.name=\"imagename\"" --file Dockerfile .took: 0.58sexited: 1
    Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

I'm not sure what you need to help me diagnose this, so here is my cluster settings

```
Id k8-cluster-profile

PluginId cd.go.contrib.elasticagent.kubernetes

go_server_url https://gocd-server-zvljz:8154/go

kubernetes_cluster_url https://172.20.0.1:443

namespace gocdpjv5l
```

and here are the elastic agent settings

```
    Image gocd-agent-docker-dind:v20.1.0

    PodConfiguration
    "apiVersion": "v1"
    "kind": "Pod"
    "metadata":
      "labels":
        "app": "web"
      "name": "gocd-agent-{{ POD_POSTFIX }}"
      "namespace": "gocdpjv5l"
    "spec":
      "containers":
      - "image": "gocd/gocd-agent-docker-dind:v20.1.0"
        "name": "gocd-agent-container-{{ CONTAINER_POSTFIX }}"
        "namespace": "gocdpjv5l"
        "volumeMounts":
        - "mountPath": "/home/go/.ssh"
          "name": "ssh-secrets"
          "readOnly": true
      "securityContext":
        "privileged": true
      "serviceAccountName": "gocd-km2p9"
      "volumes":
      - "name": "ssh-secrets"
        "secret":
          "secretName": "gocd-agent-ssh-xtgct"

    PodSpecType    yaml

    Privileged    true
```

**Comment by varshavaradarajan** [comment]
The `privileged: true` should be specified per container. `privileged` is not a valid option in the pod security context. Change the indentation on the security context?  

https://kubernetes.io/docs/concepts/workloads/pods/pod/#privileged-mode-for-pod-containers

> Any container in a Pod can enable privileged mode, using the privileged flag on the security context of the container spec.

**Comment by josh-stableprice** [comment]
> The `privileged: true` should be specified per container. `privileged` is not a valid option in the pod security context. Change the indentation on the security context?
> 
> https://kubernetes.io/docs/concepts/workloads/pods/pod/#privileged-mode-for-pod-containers
> 
> > Any container in a Pod can enable privileged mode, using the privileged flag on the security context of the container spec.

Good spot, looks like my yaml was deindented -.-
