### ISSUE TITLE
Unable to modify wrapper-properties.conf

### ISSUE THREAD

**Issue by erd0s** [gocd/docker-gocd-agent-dind#11]
I'd like to set `go.agent.status.api.bind.host=0.0.0.0` in my wrapper properties file so that I can have healthchecks on the agent from outside the container, but as far as I can tell it's not possible to modify wrapper-properties.conf because of [this line](https://github.com/gocd/docker-gocd-agent-dind/blob/master/docker-entrypoint.sh#L130) in the docker-entrypoint.sh file (usage of `>` instead of `>>` overwrites the existing file).

Is this by design? Or would it make sense to change it to something like:

```bash
echo "wrapper.app.parameter.100=-serverUrl" >> /go-agent/wrapper-config/wrapper-properties.conf
```

..allowing the file to be linked from the godata directory and not be overwritten?

Happy to put in a PR with updated readme, let me know

**Comment by m-makuch** [comment]
Made a PR with suggested solution
https://github.com/gocd/docker-gocd-agent-dind/pull/12

**Comment by ketan** [comment]
Try passing `-e AGENT_STARTUP_ARGS=-Dgo.agent.status.api.bind.host=0.0.0.0`?

**Comment by erd0s** [comment]
Ah, right, yes that works perfectly thanks @ketan
