### ISSUE TITLE
file is mounted as directory for broken docker storage drivers

### ISSUE THREAD

**Issue by pPanda-beta** [gocd/docker-gocd-agent-dind#14]
# Problem:
When we are mounting a file inside gocd/gocd-agent-docker-dind:v20.1.0, the file is getting mounted as directory. 

# Steps to reproduce

## oneliner inside container
```bash
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock docker:19.03.8-dind sh -c ' \
        echo "simple text file created inside container" > /tmp/file ; \
        docker run --rm -it -v /tmp/file:/home/go/somefolder/somefile gocd/gocd-agent-docker-dind:v20.1.0  cat /home/go/somefolder/somefile ; \
'
```

## Or do it in your unix/osx system - (This is not happening all systems)
1. `echo "simple text file created inside host" > /tmp/file `
2. `docker run --rm -it -v /tmp/file:/home/go/somefolder/somefile gocd/gocd-agent-docker-dind:v20.1.0  cat /home/go/somefolder/somefile`

## Expected Output

```
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
$ exec /usr/local/sbin/tini -g -- cat /home/go/somefolder/somefile
simple text file created inside container
```

## Actual output 
```
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
$ exec /usr/local/sbin/tini -g -- cat /home/go/somefolder/somefile
cat: read error: Is a directory
```

You can further investigate by `ls -al  /home/go/somefolder ` or may be ` [ -d /home/go/somefolder/somefile ]`

# Why so serious ?
This might look a trivial problem, but in reality it isn’t. I am using **docker-elastic-agents-plugin**, to spin up elastic agents, based on image : `gocd/gocd-agent-docker-dind:v20.1.0`
Now from inside the container, to take a pull from a private git repository over ssh, I had to mount the ssh keys on following locations: 

- /home/go/.ssh/id_rsa
- /home/go/.ssh/config
- /home/go/.ssh/known_hosts

**THIS STUPID PROBLEM IS MOUNTING THE PRIVATE KEY `id_rsa`, AS DIRECTORY AND WASTED TWO FULL WORKING DAYS OF MINE.** 

Docker info for debugging : 
```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 86
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 2.432GiB
 Name: docker-desktop
 ID: JPA6:3U75:KKBL:OBPH:2YIF:HQOS:QNAD:SOXL:HMZS:3REY:47FJ:UYG7
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 41
  Goroutines: 56
  System Time: 2020-04-25T14:29:44.333396655Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  172.21.255.199:5000
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

```

**Comment by GaneshSPatil** [comment]
Hi @pPanda-beta 

I tried the steps mentioned to reproduce the issue, and it works fine:

```bash
➜  ~ echo "simple text file created inside host" > /tmp/file
➜  ~ docker run --rm -it -v /tmp/file:/home/go/somefolder/somefile gocd/gocd-agent-docker-dind:v20.1.0 cat /home/go/somefolder/somefile
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
$ exec /usr/local/sbin/tini -g -- cat /home/go/somefolder/somefile
simple text file created inside host
```

I found ["Mounting host file to docker container creates directory in the container instead of file"](https://forums.docker.com/t/mounting-host-file-to-docker-container-creates-directory-in-the-container-instead-of-file/19729/1)  on the docker forum. Can you check if any of the suggestions work for you to resolve this issue?

**Comment by varshavaradarajan** [comment]
@pPanda-beta - also, why can't you mount `/home/go/.ssh` as a directory?

**Comment by GaneshSPatil** [comment]
@pPanda-beta - The following comment might not be applicable for you, as from the provided steps to reproduce, it can be seen that you're not using relative paths.

After spending some more time on the issue, found out that docker does not understand relative paths for volume mounts. So, for docker, no file exists on the provided relative path. And for **the bind-mount a file or directory that does not exist on the Docker host, `-v` option always creates a directory endpoint inside the container.**

#### When provided relative path
```bash
➜  echo "simple text file created inside host" > junk.txt

➜  ls junk.txt
junk.txt

➜  docker run --rm -it -v junk.txt:/home/go/somefolder/somefile gocd/gocd-agent-docker-dind:v20.1.0 cat /home/go/somefolder/somefile
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
$ exec /usr/local/sbin/tini -g -- cat /home/go/somefolder/somefile
cat: read error: Is a directory

➜  docker run --rm -it -v junk.txt:/home/go/somefolder/somefile gocd/gocd-agent-docker-dind:v20.1.0 ls -alh /home/go/somefolder
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
$ exec /usr/local/sbin/tini -g -- ls -alh /home/go/somefolder
total 12K
drwxr-sr-x    3 root     root        4.0K Apr 25 18:17 .
drwxr-sr-x    1 go       root        4.0K Apr 25 18:17 ..
drwxr-xr-x    2 root     root        4.0K Apr 25 18:03 somefile
```

#### When provided absolute path
```bash
➜  echo "simple text file created inside host" > junk.txt

➜  ls junk.txt
junk.txt

➜  docker run --rm -it -v $(pwd)/junk.txt:/home/go/somefolder/somefile gocd/gocd-agent-docker-dind:v20.1.0 ls -alh /home/go/somefolder
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
$ exec /usr/local/sbin/tini -g -- ls -alh /home/go/somefolder
total 12K
drwxr-sr-x    2 root     root        4.0K Apr 25 18:18 .
drwxr-sr-x    1 go       root        4.0K Apr 25 18:18 ..
-rw-r--r--    1 go       root          37 Apr 25 18:18 somefile

➜  docker run --rm -it -v $(pwd)/junk.txt:/home/go/somefolder/somefile gocd/gocd-agent-docker-dind:v20.1.0 ls -alh /home/go/somefolder
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
$ exec /usr/local/sbin/tini -g -- ls -alh /home/go/somefolder
total 12K
drwxr-sr-x    2 root     root        4.0K Apr 25 18:18 .
drwxr-sr-x    1 go       root        4.0K Apr 25 18:18 ..
-rw-r--r--    1 go       root          37 Apr 25 18:18 somefile
```

**Comment by sabyasachi-nandy** [comment]
@varshavaradarajan I did exactly the same that you mentioned above,
i.e. the following volume mount while setting up the elastic profile.
`/home/go/.ssh:/home/go/.ssh`

Since the gocd server was also running as a docker container and the ssh keys were mounted from outside, I tried to forward those to the elastic container. 
Now the folder mounting from host to the gocd server container worked fine, and server was able to take pull from private repository. 

Now when I mounted the same folder to the elastic container,
i.e.
host ---> gocd server container ---> gocd elastic container
The results were quite confusing, and that's why I didn't put it here to keep the focus on the particular issue. 
The results were : 

- /home/go/.ssh/id_rsa - as directory
- /home/go/.ssh/id_rsa.pub - as file
- /home/go/.ssh/config - as directory
- /home/go/.ssh/known_hosts - as directory
- /home/go/.ssh/authorized_keys - as file

Only God knows what is happening between those containers. 
I also tried mounting the volumes as read only, but the results were same.

**Comment by pPanda-beta** [comment]
@varshavaradarajan I did exactly the same that you mentioned above,
i.e. the following volume mount while setting up the elastic profile.
`/home/go/.ssh:/home/go/.ssh`

Since the gocd server was also running as a docker container and the ssh keys were mounted from outside, I tried to forward those to the elastic container. 
Now the folder mounting from host to the gocd server container worked fine, and server was able to take pull from private repository. 

Now when I mounted the same folder to the elastic container,
i.e.
host ---> gocd server container ---> gocd elastic container
The results were quite confusing, and that's why I didn't put it here to keep the focus on the particular issue. 
The results were : 

- /home/go/.ssh/id_rsa - as directory
- /home/go/.ssh/id_rsa.pub - as file
- /home/go/.ssh/config - as directory
- /home/go/.ssh/known_hosts - as directory
- /home/go/.ssh/authorized_keys - as file

Only God knows what is happening between those containers. 
I also tried mounting the volumes as read only, but the results were same.

**Comment by pPanda-beta** [comment]
@GaneshSPatil I tried the steps for "real host to container mounting" on a different laptop and it worked correctly as yours. 
To avoid any "it works on my machine" scenario, lets try the "container to container mounting" only. 

```bash
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock docker:19.03.8-dind sh -c ' \
        echo "simple text file created inside container" > /tmp/file ; \
        docker run --rm -it -v /tmp/file:/home/go/somefolder/somefile gocd/gocd-agent-docker-dind:v20.1.0  cat /home/go/somefolder/somefile ; \
'
```

This produced incorrect results on **two different macbooks and also on a debian based gcp VM.**  I would call that highly consistent behaviour :P :P 

Also, I would like to know the `docker version` of yours. If we look carefully, in every possible way, the systems are using host's docker daemon only. I have a hunch that, the problem happens with `gocd/gocd-agent-docker-dind:v20.1.0 ` and `docker ce 19.03.x`

**Comment by GaneshSPatil** [comment]
Unfortunately, it works on my machine :/

### Docker version
```bash
➜  docker --version
Docker version 19.03.8, build afacb8b

➜  docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### Output of the command
```bash
➜  docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock docker:19.03.8-dind sh -c ' \
        echo "simple text file created inside container" > /tmp/file ; \
        docker run --rm -it -v /tmp/file:/home/go/somefolder/somefile gocd/gocd-agent-docker-dind:v20.1.0  cat /home/go/somefolder/somefile ; \
'
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
$ exec /usr/local/sbin/tini -g -- cat /home/go/somefolder/somefile
simple text file created inside host
```

---

I feel its the problem with docker configurations.

@pPanda-beta Can you check your file sharing configurations under docker preferences to know whether `/tmp` directory can be used as a bind mount for containers?

<img width="1080" alt="Screen Shot 2020-04-26 at 8 35 34 PM" src="https://user-images.githubusercontent.com/15275847/80311511-a8ff4a00-87fd-11ea-87a5-042893e449c3.png">

When a file/directory is volume mounted from the path which is not allowed for file sharing, such files are not accessible by docker, and produces the result mentioned by you.

### When `/tmp` is allowed for volume file sharing:
```bash
➜  docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock docker:19.03.8-dind sh -c ' \
        echo "simple text file created inside container" > /tmp/file ; \
        docker run --rm -it -v /tmp/file:/home/go/somefolder/somefile gocd/gocd-agent-docker-dind:v20.1.0  cat /home/go/somefolder/somefile ; \
'
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
$ exec /usr/local/sbin/tini -g -- cat /home/go/somefolder/somefile
simple text file created inside host
```

### When `/tmp` is not allowed for volume file sharing:
```bash
➜  docker-examples docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock docker:19.03.8-dind sh -c ' \
        echo "simple text file created inside container" > /tmp/file ; \
        docker run --rm -it -v /tmp/file:/home/go/somefolder/somefile gocd/gocd-agent-docker-dind:v20.1.0  cat /home/go/somefolder/somefile ; \
'
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
$ exec /usr/local/sbin/tini -g -- cat /home/go/somefolder/somefile
cat: read error: Is a directory
```

\cc: @varshavaradarajan @arvindsv

**Comment by pPanda-beta** [comment]
@GaneshSPatil I checked this with both the settings, the result is same,

Also I've raised another issue on dind : https://github.com/docker-library/docker/issues/228

There I used a different  location and it still produced the same problem
```bash
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock docker:19.03.8-dind sh -c ' \
        echo "simple text file created inside container" > /root/file ; \
        docker run --rm -it -v /root/file:/somefile docker:19.03.8-dind  cat /somefile ; \
'
```

And the scenario you mentioned is not applicable on the debian VM I tried.

**Comment by pPanda-beta** [comment]
The simple use case has been explained on : https://github.com/docker-library/docker/issues/228 

# It looks like trouble will come if we start using DOOD, on DIND mode this problem will not occur.
 
on DOOD mode, it is supposed to mount /home/go/.ssh from physical machine to the elastic agent directly.

Will investigate further and update on this ticket.

**Comment by pPanda-beta** [comment]
Closing this ticket since, its the wrong usage of DIND
