### ISSUE TITLE
Rake is not installed

### ISSUE THREAD

**Issue by ck99** [gocd/docker-gocd-agent-dind#2]
I was following the instructions to test GoCD in Kubernetes, and got as far as the step to deploy the built and tested app, but the deploy step fails (following the instructions)

output:
```
[go] Task: fetch artifact [pluggable-artifact-metadata/cd.go.artifact.docker.registry.json] => [] from [build_and_publish_image/test_application/build_and_publish_image/build_and_publish_image]took: 0.30s
[go] Fetching artifact [pluggable-artifact-metadata/cd.go.artifact.docker.registry.json] from [build_and_publish_image/7/build_and_publish_image/1/build_and_publish_image]
[go] Saved artifact to [pipelines/deploy_app_to_cluster/cd.go.artifact.docker.registry.json] after verifying the integrity of its contents.
[go] Task status: passed, took: 0.30s
[go] Task: bash -c "PLUGIN_FILENAME=cd.go.artifact.docker.registry.json rake create_json"took: 0.111s, exited: 127
bash: rake: command not found
[go] Task status: failed, took: 0.111s, exited: 127
[go] Current job status: failed
```

I believe whats missing is `apk add ruby-rake` in the Dockerfile.

**Comment by varshavaradarajan** [comment]
@ck99 - For the gocd agent images, we provide only the minimal packages required to run the gocd agent and to fetch from a source repository. You may want rake and somebody else might want some other package installed. We chose to keep the agent image minimal. You could create your own docker image from this base image using the `FROM gocd/gocd-agent-alpine-3.8:v18.9.0` instruction and use your custom image.

**Comment by ck99** [comment]
OK, I understand.

It's not that I particularly want rake, but I was following these instructions which fail because rake is not available.

https://docs.gocd.org/current/gocd_on_kubernetes/designing_a_cd_pipeline/creating_a_deploy_pipeline.html

also, this page refers to troubleshooting an issue where Rake is not available

https://docs.gocd.org/current/installation/troubleshooting.html#path_issues

**Comment by varshavaradarajan** [comment]
@ck99 - thanks for bringing it up. We'll take a look and fix the instructions.

**Comment by ck99** [comment]
@varshavaradarajan - no problem.

I guess if you are gonna change the instructions, then you'll also need to change the demo application (https://github.com/gocd-demo/node-bulletin-board/commit/be9c8d0e479a7b0ecb2c11a4d45d5f989eae14aa)

Best wishes!
